name: graphql-inspector
on: [push]

permissions:
  contents: read 
  pull-requests: write
  checks: write


jobs:
  graphql-inspector:
    name: Validate Schema
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:src/graphql/schema/ecs-service-schema.graphql'