name: Validate Graphql Schema Changes
# Graphql Inspector was suggested by the graphql community to check if any breaking changes introduced in the Graphql API.
# https://the-guild.dev/graphql/inspector/docs/products/action
on: [push]

permissions:
  contents: write

jobs:
  test:
    name: Validate Schema
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:src/graphql/schema/ecs-service-schema.graphql'
          github-token: ${{ secrets.GITHUB_TOKEN }}