name: CI

on: [push]

jobs:
  test:
    name: Validate Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:src/graphql/ecs-service-schema.graphql'