name: Validate Graphql Schema Changes
on: [push]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout
  pull-requests: write
  # actions: write
  # deployments: write
  # issues: write
  # repository-projects: write
  checks: write


jobs:
  graphql-inspector:
    name: Validate Schema
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:src/graphql/schema/ecs-service-schema.graphql'