name: Validate Graphql Schema Changes
on: [push]

jobs:
  graphql-inspector:
    name: Validate Schema
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      repository-projects: write
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:src/graphql/schema/ecs-service-schema.graphql'
          # github_token: ${{ secrets.PAT_TOKEN }}