name: CI

on: [push]

jobs:
  test:
    name: Validate Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:ecs-service-schema.graphql'