name: Validate Graphql Schema Changes
on: [push]

permissions:
  contents: read    # This is required for actions/checkout
  pull-requests: read
  checks: read


jobs:
  graphql-inspector:
    name: Validate Schema
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:src/graphql/schema/ecs-service-schema.graphql'