name: Unit Tests
on: 
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '!**.md'
env:
  NODE_ENV: test

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          TEST_FOLDER="$(find . -type d -maxdepth 1 -name 'test')"
          if [[ -z $TEST_FOLDER ]]; then
            echo "No test folder detected."
            exit 0
          fi
          
          for TEST_DIR in $TEST_FOLDER; do
            if jq -e '.scripts | has("test")' package.json > /dev/null; then
              echo "Running tests in $TEST_DIR"
              pnpm test
            fi
          done